window.LY10_DATA={
  version:'1.4.1',
  fixture:{opponent:'Rayo Vallecano',competition:'La Liga',home:'FC Barcelona',date:'2026-08-31T21:30:00+02:00'},
  stats:[['GOALS',0,'2026/27 La Liga','Official league total.'],['ASSISTS',0,'2026/27 La Liga','Official league total.'],['MATCHES',2,'2026/27 La Liga','League appearances.'],['MINUTES',155,'2026/27 La Liga','League minutes played.']],
  poll:{id:'best-weapon',question:'WHAT IS HIS BEST WEAPON?',options:['Dribbling','Vision','Finishing','Composure']},
  quiz:[{q:'At what age did Lamine make his Barcelona first-team debut?',answers:['14','15','16'],correct:1},{q:'Which position is most associated with Lamine?',answers:['Right wing','Centre-back','Goalkeeper'],correct:0},{q:'Which academy helped shape his game?',answers:['La Masia','Ajax Academy','Cobham'],correct:0},{q:'Which country does he represent internationally?',answers:['Spain','Morocco','Equatorial Guinea'],correct:0}],
  facts:['Lamine joined FC Barcelona at the age of seven.','His first club was CF La Torreta.','He became the youngest scorer in UEFA EURO history in 2024.','In 2026 he became the youngest player to win both the European Championship and the World Cup.'],
  matches:{'6':{title:'Valencia vs Barça',meta:'La Liga · Away · 16:15 CEST',note:'Mestalla.'},'9':{title:'Barça vs Feyenoord',meta:'Champions League · Home · 18:45 CEST',note:'Spotify Camp Nou.'},'13':{title:'Levante vs Barça',meta:'La Liga · Away · Time TBA',note:'Ciutat de Valencia.'},'16':{title:'Barça vs Racing de Santander',meta:'La Liga · Home · Time TBA',note:'Spotify Camp Nou.'},'20':{title:'Sevilla vs Barça',meta:'La Liga · Away · Time TBA',note:'Ramón Sánchez-Pizjuán.'}},
  sections:[['Match Centre','match-centre','Latest result, next fixture, standings and MOTM.'],['Player Stats','stats','Goals, assists, minutes and the dedicated 2026/27 tracker.'],['The Story','story','From Rocafonda and La Masia to the first-team stage.'],['Signature Moments','moments','Barça debut, EURO 2024 and record-breaking milestones.'],['Photo Gallery','gallery','Captioned photos and key frames from Yamal’s journey.'],['Fan Zone','fan-zone','Polls, feedback and community features.'],['Beyond Football','beyond','Family roots, role models, UNICEF and the personal story.']],
  worldCup:{label:'05 / WORLD CHAMPION',title:'WORLD CUP<br /><em>WINNER.</em>',tournament:'2026 FIFA WORLD CUP',team:'Spain',status:'Champions · July 2026',form:'Spain defeated Argentina in the 2026 final, with Lamine Yamal starting for the world champions.',record:{appearances:'World Cup finalist',goals:'Scored at 18',assists:'Official sources',tournaments:'EURO 2024 · WORLD CUP 2026'},road:[['Group Stage','complete'],['Round of 16','complete'],['Quarter-final','complete'],['Semi-final','complete'],['Final','champions']]}
};