window.LY10_DATA={
  version:'1.3.0',fixture:{opponent:'Sevilla',competition:'La Liga',home:'Barça',date:'2026-08-17T19:00:00+01:00'},
  stats:[['GOALS',18,'2025/26 all competitions','A season total — update after each match.'],['ASSISTS',22,'Creative output','Includes match-winning final-ball moments.'],['CHANCES CREATED',87,'Season total','Fan data; providers may use different definitions.'],['TAKE-ONS WON',126,'1v1 moments','Successful dribbles and carries.']],
  poll:{id:'best-weapon',question:'WHAT IS HIS BEST WEAPON?',options:['Dribbling','Vision','Finishing','Composure']},
  quiz:[{q:'At what age did Lamine make his Barcelona first-team debut?',answers:['14','15','16'],correct:1},{q:'Which position is most associated with Lamine?',answers:['Right wing','Centre-back','Goalkeeper'],correct:0},{q:'Which academy helped shape his game?',answers:['La Masia','Ajax Academy','Cobham'],correct:0},{q:'Which country does he represent internationally?',answers:['Spain','Morocco','Equatorial Guinea'],correct:0}],
  facts:['Lamine joined FC Barcelona at the age of seven.','His first club was CF La Torreta.','He became the youngest scorer in UEFA EURO history in 2024.','His left foot and right-wing starting position create his signature angle.'],
  matches:{'3':{title:'Barça vs Girona',meta:'La Liga · Home',note:'Update kick-off, squad news and official broadcast links here.'},'6':{title:'Sevilla vs Barça',meta:'La Liga · Away',note:'Away-day match centre: score prediction, starting XI and rating cards.'},'14':{title:'Barça vs Valencia',meta:'La Liga · Home',note:'Matchday briefing: add official club news and final result.'},'21':{title:'Atlético vs Barça',meta:'La Liga · Away',note:'Big-game tracker: ratings and reactions unlock after full time.'}},
  sections:[['Match Centre','match-centre','Latest result, next fixture, standings and MOTM.'],['Player Stats','stats','Goals, assists, heat map, comparison and season pulse.'],['The Story','story','From Rocafonda and La Masia to the first-team stage.'],['Signature Moments','moments','Barça debut, EURO 2024 and record-breaking milestones.'],['Photo Gallery','gallery','Captioned photos and key frames from Yamal’s journey.'],['Fan Zone','fan-zone','Polls, feedback and community features.'],['Beyond Football','beyond','Family roots, role models, UNICEF and the personal story.']],
  worldCup:{label:'05 / WORLD CUP ROAD',title:'WORLD CUP<br /><em>DREAMS.</em>',tournament:'2026 FIFA WORLD CUP',team:'Spain',status:'Tournament preparation',form:'Spain are building toward the next global stage.',record:{appearances:'—',goals:'—',assists:'—',tournaments:'UEFA EURO 2024'},road:[['Group Stage','upcoming'],['Round of 16','upcoming'],['Quarter-final','upcoming'],['Semi-final','upcoming'],['Final','upcoming']]}
};
