const themeButton=document.querySelector('#theme-toggle');themeButton?.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('ly10-theme',document.body.classList.contains('dark')?'dark':'light')});if(localStorage.getItem('ly10-theme')==='dark')document.body.classList.add('dark');
document.querySelectorAll('[data-poll]').forEach(b=>b.addEventListener('click',()=>{const note=document.querySelector('#poll-note');if(note)note.textContent=`Vote recorded for ${b.dataset.poll} ✓`;document.querySelectorAll('[data-poll]').forEach(x=>x.disabled=true)}));
const pageUrl=encodeURIComponent(location.href);const whatsApp=document.querySelector('.share-whatsapp'),shareX=document.querySelector('.share-x');if(whatsApp)whatsApp.href=`https://wa.me/?text=${encodeURIComponent('LY10 — The Lamine Yamal fanbase: ')}${pageUrl}`;if(shareX)shareX.href=`https://x.com/intent/post?text=${encodeURIComponent('Checking out LY10 — the independent Lamine Yamal fanbase')}&url=${pageUrl}`;
document.querySelectorAll('#feedback-form,#newsletter-form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const msg=form.querySelector('.form-message');if(msg)msg.textContent='Thanks — your note is saved locally for this demo.';form.reset()}));document.querySelector('#wallpaper-button')?.addEventListener('click',e=>{e.currentTarget.textContent='YOU’RE ON THE LIST ✓'});document.querySelector('#comment-button')?.addEventListener('click',()=>alert('Comments will open when moderation is connected.'));
const topButton=document.querySelector('.back-top');addEventListener('scroll',()=>topButton?.classList.toggle('show',scrollY>500),{passive:true});topButton?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));

// Mobile resilience: cache the site shell so repeat visits survive weak or temporary connections.
if('serviceWorker' in navigator){addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{})})}

// Small connection-status notice. It appears only when the device is offline.
(()=>{const notice=document.createElement('div');notice.id='connection-notice';notice.setAttribute('role','status');notice.setAttribute('aria-live','polite');Object.assign(notice.style,{position:'fixed',left:'50%',bottom:'78px',transform:'translateX(-50%)',zIndex:'100',background:'#07182d',color:'#fff',padding:'9px 13px',border:'1px solid #f8c725',font:'10px DM Mono, monospace',letterSpacing:'.04em',display:'none',maxWidth:'calc(100vw - 28px)',textAlign:'center'});document.body.appendChild(notice);const sync=()=>{if(navigator.onLine){notice.style.display='none';notice.textContent=''}else{notice.textContent='You’re offline — LY10 is using the saved version.';notice.style.display='block'}};addEventListener('online',sync);addEventListener('offline',sync);sync()})();
